const assert = require('assert')
const conv = require('../src/conv.js')

console.log('conv(6, 8)')
const six2eight = conv(6, 8)
assert.deepStrictEqual(six2eight([]), [])
assert.deepStrictEqual(six2eight([5]), [5])
assert.deepStrictEqual(six2eight([1, 0]), [6])
assert.deepStrictEqual(six2eight([1, 1]), [7])
assert.deepStrictEqual(six2eight([1, 2]), [1, 0])
assert.deepStrictEqual(six2eight([1, 2, 1, 3]), [4, 5, 1])
console.log()

console.log('conv(8, 6)')
const eight2six = conv(8, 6)
assert.deepStrictEqual(eight2six([]), [])
assert.deepStrictEqual(eight2six([5]), [5])
assert.deepStrictEqual(eight2six([6]), [1, 0])
assert.deepStrictEqual(eight2six([7]), [1, 1])
assert.deepStrictEqual(eight2six([1, 0]), [1, 2])
assert.deepStrictEqual(eight2six([4, 5, 1]), [1, 2, 1, 3])
console.log()

console.log('conv() 6 to 10 to 8')
assert.deepStrictEqual(conv(6, 10)([1, 2, 1, 3]), [2, 9, 7])
assert.deepStrictEqual(conv(10, 6)([2, 9, 7]), [1, 2, 1, 3])
assert.deepStrictEqual(conv(8, 10)([4, 5, 1]), [2, 9, 7])
assert.deepStrictEqual(conv(10, 8)([2, 9, 7]), [4, 5, 1])
console.log()

console.log('conv() bug')
assert.deepStrictEqual(conv(5, 65537)([1]), [1])
assert.deepStrictEqual(conv(65537, 5)([1]), [1])
console.log()
